# Configuration file for golangci-lint
#
# https://github.com/golangci/golangci-lint
#
# fighting with false positives?
# https://github.com/golangci/golangci-lint#nolint

linters:
  enable:
    - gofmt # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification [fast: true, auto-fix: true]
    - goimports # Goimports does everything that gofmt does. Additionally it checks unused imports [fast: true, auto-fix: true]
    - misspell # Finds commonly misspelled English words in comments [fast: true, auto-fix: true]
    - govet

    - bodyclose # checks whether HTTP response body is closed successfully [fast: false, auto-fix: false]
    - depguard # Go linter that checks if package imports are in a list of acceptable packages [fast: true, auto-fix: false]
    - dupl # Tool for code clone detection [fast: true, auto-fix: false]
    - copyloopvar # Replaces exportloopref
    - gochecknoinits # Checks that no init functions are present in Go code [fast: true, auto-fix: false]
    - goconst # Finds repeated strings that could be replaced by a constant [fast: true, auto-fix: false]
    - gocyclo # Computes and checks the cyclomatic complexity of functions [fast: true, auto-fix: false]
    - gosimple # Linter for Go source code that specializes in simplifying a code [fast: false, auto-fix: false]
    - ineffassign # Detects when assignments to existing variables are not used [fast: true, auto-fix: false]
    - nakedret # Finds naked returns in functions greater than a specified function length [fast: true, auto-fix: false]
    - prealloc # Finds slice declarations that could potentially be preallocated [fast: true, auto-fix: false]
    - revive # Replaced golint
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks [fast: false, auto-fix: false]
    - stylecheck # Stylecheck is a replacement for golint [fast: false, auto-fix: false]
    - typecheck # Like the front-end of a Go compiler, parses and type-checks Go code [fast: true, auto-fix: false]
    - unconvert # Remove unnecessary type conversions [fast: true, auto-fix: false]
    - unused # Checks Go code for unused constants, variables, functions and types [fast: false, auto-fix: false]
  disable:
    # Don't care about line length, this is Go
    - lll # Reports long lines [fast: true, auto-fix: false]

    # Global variables are fine
    - gochecknoglobals # Checks that no globals are present in Go code [fast: true, auto-fix: false]

    # Too much opinion
    - gocritic # The most opinionated Go source code linter [fast: true, auto-fix: false]

    # Gosec just runs errcheck, which alerts on unchecked errors in defer'd
    # file closes, which is generally not useful.
    - errcheck # Inspects source code for security problems [fast: true, auto-fix: false]
    - gosec # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases [fast: true, auto-fix: false]

    # Implementing interfaces can cause this to happen all the time
    - unparam # Reports unused function parameters [fast: false, auto-fix: false]
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/AstromechZA/etcpwdparse
          - github.com/BurntSushi/toml
          - github.com/creack/pty
          - github.com/docker/docker
          - github.com/docker/go-connections
          - github.com/mattn/go-isatty
          - github.com/sbinet/pstree
          - github.com/sirupsen/logrus
          - github.com/pkg/errors
          - github.com/vektra/tai64n
          - goji.io
          - golang.org/x/crypto
          - golang.org/x/exp
          - golang.org/x/net
          - golang.org/x/sys
          - golang.org/x/term
          - gotest.tools
          - hop.computer/hop

  goimports:
    local-prefixes: hop.computer/hop
  govet:
    disable:
      - shadow
      - fieldalignment
    enable:
      - asmdecl
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      
issues:
  exclude-dirs:
    - cmd/hop
  exclude-files:
    - .*keccakf_amd64.s
    - .*keccakf_amd64.go
  exclude-use-default: false
  exclude:
    - G104 # 'Errors unhandled. (gosec)
    - G204 # Subprocess launched with variable (gosec)
    - G301 # Expect directory permissions to be 0750 or less (gosec)
    - G302 # Expect file permissions to be 0600 or less (gosec)
    - G304 # Potential file inclusion via variable (gosec)

