version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - gochecknoinits
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
  disable:
    # Don't care about this
    - depguard

    # Usually this just yells about defer'd file closes
    - errcheck

    # Global variables are fine
    - gochecknoglobals

    # Overly opinionated about when to switch from a string to a const
    - goconst

    # Too much opinion
    - gocritic

    # Don't care about line length, this is Go
    - lll
    - unparam
  settings:
    govet:
      enable:
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - errorsas
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
      disable:
        - fieldalignment

        # We like to shadow `err`
        - shadow
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks:
         - "-QF1003"
         - "U1000"
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: G104 # 'Errors unhandled. (gosec)
      - path: (.+)\.go$
        text: G115 # Integer overflow conversion (gosec), we do this a lot and it doesn't catch when you check the size first.
      - path: hopserver/session.go
        text: G204 # Subprocess launched with variable (gosec), that is the whole point of Hop.
      - path: (.+).go$
        text: G304 # Potential file inclusion via variable (gosec), we have a lot of functions that read files.
    paths:
      - .*keccakf_amd64.s
      - .*keccakf_amd64.go
      - cmd/hop
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - hop.computer/hop
  exclusions:
    generated: lax
    paths:
      - .*keccakf_amd64.s
      - .*keccakf_amd64.go
      - cmd/hop
      - third_party$
      - builtin$
      - examples$
