version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dupl
    - gochecknoinits
    - goconst
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
  disable:
    - errcheck
    - gochecknoglobals
    - gocritic
    - lll
    - unparam
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - go.uber.org/goleak
            - github.com/AstromechZA/etcpwdparse
            - github.com/BurntSushi/toml
            - github.com/charmbracelet/bubbletea
            - github.com/charmbracelet/lipgloss
            - github.com/creack/pty
            - github.com/docker/docker
            - github.com/docker/go-connections
            - github.com/google/go-cmp/cmp
            - github.com/mattn/go-isatty
            - github.com/muesli/cancelreader
            - github.com/sbinet/pstree
            - github.com/sirupsen/logrus
            - github.com/pkg/errors
            - goji.io
            - golang.org/x/crypto
            - golang.org/x/exp
            - golang.org/x/net
            - golang.org/x/sys
            - golang.org/x/term
            - gotest.tools
            - hop.computer/hop
    govet:
      enable:
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - errorsas
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
      disable:
        - shadow
        - fieldalignment
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: G104
      - path: (.+)\.go$
        text: G115
      - path: (.+)\.go$
        text: G204
      - path: (.+)\.go$
        text: G301
      - path: (.+)\.go$
        text: G302
      - path: (.+)\.go$
        text: G304
    paths:
      - .*keccakf_amd64.s
      - .*keccakf_amd64.go
      - cmd/hop
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - hop.computer/hop
  exclusions:
    generated: lax
    paths:
      - .*keccakf_amd64.s
      - .*keccakf_amd64.go
      - cmd/hop
      - third_party$
      - builtin$
      - examples$
