// Code generated by "stringer -type NodeType ."; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeTypeFile-0]
	_ = x[NodeTypeSetting-1]
	_ = x[NodeTypeBlock-2]
}

const _NodeType_name = "NodeTypeFileNodeTypeSettingNodeTypeBlock"

var _NodeType_index = [...]uint8{0, 12, 27, 40}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
