// Code generated by "stringer -type TokenType ."; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenTypeKeyword-0]
	_ = x[TokenTypeInt-1]
	_ = x[TokenTypeFloat-2]
	_ = x[TokenTypeScope-3]
	_ = x[TokenTypeEnd-4]
	_ = x[TokenTypeString-5]
}

const _TokenType_name = "TokenTypeKeywordTokenTypeIntTokenTypeFloatTokenTypeScopeTokenTypeEndTokenTypeString"

var _TokenType_index = [...]uint8{0, 16, 28, 42, 56, 68, 83}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
