// Code generated by gen_config.go. DO NOT EDIT.
package config

import (
	"fmt"
	"strconv"

	"github.com/sirupsen/logrus"
	"zmap.io/portal/config/ast"
)

func identity(s string) (string, error) {
	return s, nil
}

func bs(s string) (BoolSetting, error) {
	b, err := strconv.ParseBool(s)
	if err != nil {
		return Unset, err
	}
	if b {
		return True, nil
	}
	return False, nil
}

func loadClientConfig_Gen(c *ClientConfig, root *ast.Node) (*ClientConfig, error) {
	var hc *HostConfig
	err := root.Walk(func(n ast.Node) error {
		global := false
		if n.Parent == nil {
			global = true
		} else if n.Parent != nil && n.Parent.Type == ast.NodeTypeFile {
			global = true
		}
		switch n.Type {
		case ast.NodeTypeFile:
		case ast.NodeTypeBlock:
			switch n.BlockType {
			case "Include":
				logrus.Warnf("%q not yet implemented and %q will be ignored", "Include", n.BlockName)
			case "Host":
				c.Hosts = append(c.Hosts, HostConfig{})
				hc = &c.Hosts[len(c.Hosts)-1]
				hc.Pattern = n.BlockName
			}
		case ast.NodeTypeSetting:
			if global {
				switch n.SettingKey {
				case ast.Setting.CAFile.Value:
					result, err := identity(n.SettingValue)
					if err != nil {
						return err
					}
					c.CAFiles = append(c.CAFiles, result)
				case ast.Setting.Key.Value:
					result, err := identity(n.SettingValue)
					if err != nil {
						return err
					}
					c.Key = result
				case ast.Setting.Certificate.Value:
					result, err := identity(n.SettingValue)
					if err != nil {
						return err
					}
					c.Certificate = result
				case ast.Setting.AutoSelfSign.Value:
					result, err := bs(n.SettingValue)
					if err != nil {
						return err
					}
					c.AutoSelfSign = result
				default:
					logrus.Warnf("unknown global setting %q", n.SettingKey)
				}
			} else {
				switch n.SettingKey {
				case ast.Setting.Address.Value:
					result, err := identity(n.SettingValue)
					if err != nil {
						return err
					}
					hc.Hostname = result
				case ast.Setting.Port.Value:
					result, err := strconv.Atoi(n.SettingValue)
					if err != nil {
						return err
					}
					hc.Port = result
				case ast.Setting.AutoSelfSign.Value:
					result, err := bs(n.SettingValue)
					if err != nil {
						return err
					}
					hc.AutoSelfSign = result
				case ast.Setting.Key.Value:
					result, err := identity(n.SettingValue)
					if err != nil {
						return err
					}
					hc.Key = result
				case ast.Setting.Certificate.Value:
					result, err := identity(n.SettingValue)
					if err != nil {
						return err
					}
					hc.Certificate = result
				}
			}
		default:
			return fmt.Errorf("unknown node type %s", n.Type)
		}
		return nil
	})
	return c, err
}
