// Code generated by gen_token.go. DO NOT EDIT.
package ast

// Keyword contains definitions for all Tokens with TokenTypeKeyword. They can
// be safely compared by value.
var Keyword = struct {
	Host    Token
	Include Token
	Server  Token
}{
	Host: Token{
		Type:  TokenTypeKeyword,
		Value: "Host",
	},
	Include: Token{
		Type:  TokenTypeKeyword,
		Value: "Include",
	},
	Server: Token{
		Type:  TokenTypeKeyword,
		Value: "Server",
	},
}

// Keywords is an array containing all values from Setting
var Keywords = []Token{
	Keyword.Host,
	Keyword.Include,
	Keyword.Server,
}

// Setting contains definitions for all Tokens with TokenTypeKeyword. They can
// be safely compared by value.
var Setting = struct {
	Address       Token
	AgentURL      Token
	AutoSelfSign  Token
	CAFile        Token
	Certificate   Token
	Intermediate  Token
	Key           Token
	ListenAddress Token
	Number        Token
	Port          Token
	User          Token
	Word          Token
}{
	Address: Token{
		Type:  TokenTypeSetting,
		Value: "Address",
	},
	AgentURL: Token{
		Type:  TokenTypeSetting,
		Value: "AgentURL",
	},
	AutoSelfSign: Token{
		Type:  TokenTypeSetting,
		Value: "AutoSelfSign",
	},
	CAFile: Token{
		Type:  TokenTypeSetting,
		Value: "CAFile",
	},
	Certificate: Token{
		Type:  TokenTypeSetting,
		Value: "Certificate",
	},
	Intermediate: Token{
		Type:  TokenTypeSetting,
		Value: "Intermediate",
	},
	Key: Token{
		Type:  TokenTypeSetting,
		Value: "Key",
	},
	ListenAddress: Token{
		Type:  TokenTypeSetting,
		Value: "ListenAddress",
	},
	Number: Token{
		Type:  TokenTypeSetting,
		Value: "Number",
	},
	Port: Token{
		Type:  TokenTypeSetting,
		Value: "Port",
	},
	User: Token{
		Type:  TokenTypeSetting,
		Value: "User",
	},
	Word: Token{
		Type:  TokenTypeSetting,
		Value: "Word",
	},
}

// Settings is an array containing all values from Setting
var Settings = []Token{
	Setting.Address,
	Setting.AgentURL,
	Setting.AutoSelfSign,
	Setting.CAFile,
	Setting.Certificate,
	Setting.Intermediate,
	Setting.Key,
	Setting.ListenAddress,
	Setting.Number,
	Setting.Port,
	Setting.User,
	Setting.Word,
}
