// Code generated by "stringer -type TokenType ."; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenTypeKeyword-0]
	_ = x[TokenTypeSetting-1]
	_ = x[TokenTypeInt-2]
	_ = x[TokenTypeFloat-3]
	_ = x[TokenTypeScope-4]
	_ = x[TokenTypeEnd-5]
	_ = x[TokenTypeString-6]
	_ = x[TokenTypeSentinal-7]
}

const _TokenType_name = "TokenTypeKeywordTokenTypeSettingTokenTypeIntTokenTypeFloatTokenTypeScopeTokenTypeEndTokenTypeStringTokenTypeSentinal"

var _TokenType_index = [...]uint8{0, 16, 32, 44, 58, 72, 84, 99, 116}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
